FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json ./
RUN npm ci --quiet

COPY drizzle.config.ts ./
COPY src/db/schema.ts ./src/db/schema.ts
COPY tsconfig.json ./

CMD ["npx", "drizzle-kit", "push"]
